obj-$(CONFIG_SILEAD_FP)				+= silead/
obj-$(CONFIG_SUNWAVE_FP)			+= sunwave/
obj-$(CONFIG_CDFINGER_FP)			+= cdfinger/
obj-$(CONFIG_FPC1020_FP)			+= fpc1020/
obj-$(CONFIG_GF5288_FP)				+= gf5288/
obj-$(CONFIG_ELAN_FP)                         	+= elan/
obj-$(CONFIG_FOCALTECH_FP)			+= ft9362/
